//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Repository;

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class Categoria : IEntity
    {
        public Categoria()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public string categoryDescription { get; set; }
    
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
