//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public Producto()
        {
            this.Detalles = new HashSet<Detalle>();
        }
    
        public int productId { get; set; }
        [Required]
        public string productName { get; set; }
        [Required]
        public Nullable<int> productPrice { get; set; }
        [Required]
        public Nullable<int> productStock { get; set; }
        [Required]
        public Nullable<int> categoryId { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Detalle> Detalles { get; set; }
    }
}
