//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using Repository;

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;

    public partial class Usuario : IEntity
    {
        public Usuario()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public Nullable<int> userTypeId { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Tipos_Usuarios Tipos_Usuarios { get; set; }
    }
}
