//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public Usuario()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        [Key]
        public int userId { get; set; }
        [Required(ErrorMessage = "El nombre de usuario no puede estar vacio")]
        public string userName { get; set; }
        [Required(ErrorMessage = "El correo no puede estar vacio")]
        public string userEmail { get; set; }
        [Required(ErrorMessage = "La contraseña no puede estar vacia")]
        public string userPassword { get; set; }
        public Nullable<int> userTypeId { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Tipos_Usuarios Tipos_Usuarios { get; set; }
    }
}
